version: '3.4'

services:
  datascience:
    image: datascience
    build:
      context: .
      dockerfile: ./Dockerfile
      target: debug
    volumes:
      -./src:/app 
    ports:
      - 8000:8000
      - 5678:5678
    
